twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        listepage: ['accueil', 'services', 'vehicules', 'contact', 'mentionslegales']  
        horaires: []  

when@test:
    twig:
        strict_variables: true
